### ISSUE TITLE
Pets Position Customizable

### ISSUE THREAD

**Issue by AverageFemale** [GamerCoder215/StarCosmetics#14]
### Addition Type

Other Feature

### Description

Have the pets position be customizable within the config file so I can have it on the players shoulders or something like that.

**Comment by GamerCoder215** [comment]
That sounds like a great idea!

I may also implement it so that players can have it as a setting, whether they want to use the server default, my default, or any other customizable positions.

**Comment by AverageFemale** [comment]
Sounds good.

**Comment by GamerCoder215** [comment]
Added in [`88254cc`](https://github.com/GamerCoder215/StarCosmetics/commit/88254cc9b7174a36e01eb8d176a9327011e5a38e). v1.0.2 will be releasing shortly. 

Marking as closed.
