### ISSUE TITLE
No cosmetics when in spectator.

### ISSUE THREAD

**Issue by AverageFemale** [GamerCoder215/StarCosmetics#15]
### Addition Type

Other Feature

### Description

Disable the cosmetics when the user is invisible or in spectator.

**Comment by GamerCoder215** [comment]
This would be relatively hard to implement, and definitely not work it:
- Particles would have to depend on a player's settings, and looping through everyone would decrease performance
- Custom trails (e.g. riptide trail) would also require looping and decrease performance
- Everything else is fine, considering ground trails and a lot of other things are packed-based (the blocks aren't really there)

This seems unnecessary. A better option might be to disable seeing other players' cosmetics.
