### ISSUE TITLE
Others can hear my gui sounds

### ISSUE THREAD

**Issue by AverageFemale** [GamerCoder215/StarCosmetics#16]
### Bug Type

General Bug

### Minecraft Version

1.18.2

### Description

Whenever a player is in the starcosmetics menu and they click items, other players can also hear the sounds that are emitted from the items.

### Expected Behavior

Only the player can hear it, not others.

### Actual Behavior

Everyone can hear it.

**Comment by GamerCoder215** [comment]
I'll take a look and see what can be done.

**Comment by GamerCoder215** [comment]
Can confirm this happens. Will work on a fix for 1.0.2.

**Comment by GamerCoder215** [comment]
Draft fix in [`62b760d`](https://github.com/GamerCoder215/StarCosmetics/commit/62b760db79d65e5374356efca5f9b2a47508e36b). Tested, and works decently well.
