### ISSUE TITLE
Item trail disappear time

### ISSUE THREAD

**Issue by AverageFemale** [GamerCoder215/StarCosmetics#17]
### Addition Type

Other Feature

### Description

Allow us to change the time before the items from trails disappear.

**Comment by GamerCoder215** [comment]
Seems like a good idea for v1.0.2.

**Comment by AverageFemale** [comment]
Okay. 👍

**Comment by GamerCoder215** [comment]
Added in [`c7d38f0`](https://github.com/GamerCoder215/StarCosmetics/commit/c7d38f0bc076837106b5d312a8c5753cc09f0f80). More cosmetic-related disappear times will appear in the future.

Marking as completed.
