### ISSUE TITLE
Right clicking a pet puts it in your inventory

### ISSUE THREAD

**Issue by RatWithAFace** [GamerCoder215/StarCosmetics#67]
### Bug Type

General Bug

### Minecraft Version

1.20.1

### Description

Right-clicking a pet puts it in your inventory. A player can just steal someones pet.

### Expected Behavior

Pet should not be able to be taken off of the player

### Actual Behavior

Right-clicking a pet puts it in your inventory.

**Comment by GamerCoder215** [comment]
This happens because I didn't add an equipment look to the armor stand. 
The head it takes has no significance and the armor stand is actually still there, but it's still weird behavior nonetheless.
