### ISSUE TITLE
[ERROR] "IllegalAccessException"

### ISSUE THREAD

**Issue by wpmidia** [GamerCoder215/StarCosmetics#85]
### Bug Type

Console Errors

### Minecraft Version

1.20.1

### Description

I used version 1.2.2 of StarCosmetics and it worked perfectly until this morning when I updated to version 1.3.0!
* IllegalAccessException * and other error lines that I don't understand because I'm not a Java programmer.
My server runs version 1.20.1 of Paper Spigot.

Check the log file:
[2023-11-21-3.log](https://github.com/GamerCoder215/StarCosmetics/files/13429078/2023-11-21-3.log)

Thanks for your help!

### Expected Behavior

The expected behavior was not to present the reported errors

### Actual Behavior

Various errors displayed through the Server Console.

**Comment by GamerCoder215** [comment]
Might be something related to Paper, or just breaking API changes since 1.9. I'll take a look when I get the chance.

**Comment by wpmidia** [comment]
I updated PaperSpigot to the latest version 1.20.2-307 and now there are new errors. Check the new attached log file:
[latest.log](https://github.com/GamerCoder215/StarCosmetics/files/13466714/latest.log)

**Comment by GamerCoder215** [comment]
There's a reflection bug unique to Paper because they made the fields  private. I probably should have made them accessible just in case, but it's a simple fix.
